### ISSUE TITLE
ERROR_SEM_TIMEOUT when running sample code

### ISSUE THREAD

**Issue by MuddledBox** [synthead/timex_datalink_client#308]
To reproduce my issues... 

I run following the sample code, located here: 

https://github.com/synthead/timex_datalink_client/blob/main/docs/timex_datalink_protocol_1.md

When using the following with the Pico with the below u2f: 

https://github.com/synthead/timex-datalink-arduino/releases/tag/v1.0.0

I get: 

78 55 C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rubyserial-0.6.0/lib/rubyserial/windows.rb:73:in `write': ERROR_SEM_TIMEOUT (RubySerial::Error)
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/timex_datalink_client-0.12.1/lib/timex_datalink_client/notebook_adapter.rb:35:in `block (2 levels) in write'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/timex_datalink_client-0.12.1/lib/timex_datalink_client/notebook_adapter.rb:32:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/timex_datalink_client-0.12.1/lib/timex_datalink_client/notebook_adapter.rb:32:in `block in write'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/timex_datalink_client-0.12.1/lib/timex_datalink_client/notebook_adapter.rb:31:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/timex_datalink_client-0.12.1/lib/timex_datalink_client/notebook_adapter.rb:31:in `write'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/timex_datalink_client-0.12.1/lib/timex_datalink_client.rb:113:in `write'
        from ./timexTest.rb:132:in `<main>'

OR

when using the the following with the same Pico with the below u2f: 

https://github.com/famiclone6502/DIY_Datalink_Adapter/tree/main/pico

I get: 

78 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rubyserial-0.6.0/lib/rubyserial/windows.rb:73:in `write': ERROR_SEM_TIMEOUT (RubySerial::Error)
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/timex_datalink_client-0.12.1/lib/timex_datalink_client/notebook_adapter.rb:35:in `block (2 levels) in write'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/timex_datalink_client-0.12.1/lib/timex_datalink_client/notebook_adapter.rb:32:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/timex_datalink_client-0.12.1/lib/timex_datalink_client/notebook_adapter.rb:32:in `block in write'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/timex_datalink_client-0.12.1/lib/timex_datalink_client/notebook_adapter.rb:31:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/timex_datalink_client-0.12.1/lib/timex_datalink_client/notebook_adapter.rb:31:in `write'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/timex_datalink_client-0.12.1/lib/timex_datalink_client.rb:113:in `write'
        from ./timexTest.rb:132:in `<main>'

---
Running on Windows 11. There is no blinking on my Raspberry Pi Pico's inbuilt LED during either run. If I unplug the Pico and run, I just get "ERROR_FILE_NOT_FOUND". Both the above errors are consistent in length each time the application is run. Any ideas? Outdated gems?

**Comment by MuddledBox** [comment]
Note: I changed the following in the example code: 
serial_device: "\\\\.\\COM3",

Which is the location of my device.

**Comment by synthead** [comment]
Oh interesting!  I haven't tried this in Windows myself, but I have helped others get it working with WSL!  Let's see if we can narrow down the issue.  I don't have a Windows 11 machine, but I could see if it's reproducible with Windows 10.

I see `C:/Ruby32-x64` in your exceptions.  How did you install Ruby?

It also looks like you're calling `./timexTest.rb`!  Could you share this script?

**Comment by synthead** [comment]
Here's where the error you're seeing is defined:

https://github.com/hybridgroup/rubyserial/blob/090df6685f383497e9080a354b22af07731ece40/lib/rubyserial/windows_constants.rb#L198

Here's where the error from rubyserial is being raised:

https://github.com/hybridgroup/rubyserial/blob/090df6685f383497e9080a354b22af07731ece40/lib/rubyserial/windows.rb#L73

I did a little research, and found that `C:/Ruby32-x64` is a path that is used by [RubyInstaller](https://rubyinstaller.org/) (GitHub repo [here](https://github.com/oneclick/rubyinstaller2)).

**Comment by synthead** [comment]
I was able to reproduce it!

![image](https://github.com/synthead/timex_datalink_client/assets/820984/ad880273-e4ae-42eb-8f95-954246a83c13)

I'll take a look and see what it'll take to get this fixed, thanks!

**Comment by synthead** [comment]
I'm seeing what I can find, and also filed a bug upstream:

- https://github.com/hybridgroup/rubyserial/issues/52

This appears to be a bug with rubyserial somehow.  The timex_datalink_client lib uses serial in a super basic manner:

- It connects to the Notebook Adapter at 9600 baud with 8 data bits, no parity, and one stop bit (the rubyserial defaults)
- There are generous sleep calls between writes, which should make data transfer even less troublesome
- There are no serial read calls; timex_datalink_client simply writes data to a device (and slowly at that)

**Comment by synthead** [comment]
After some testing, I found that swapping the [rubyserial](https://rubygems.org/gems/rubyserial) gem with [serialport](https://rubygems.org/gems/serialport) works great in Windows (while also working great in Linux):

![image](https://github.com/synthead/timex_datalink_client/assets/820984/e00fc0aa-d057-480e-80e0-aa4cfa01b0c6)

I'll get a PR up to change upstream gems and fix this issue :+1:

**Comment by synthead** [comment]
Just shipped timex_datalink_client v0.12.2!

- https://github.com/synthead/timex_datalink_client/releases/tag/v0.12.2
- https://rubygems.org/gems/timex_datalink_client/versions/0.12.2

To update timex_datalink_client on your installation, do:

```
gem update timex_datalink_client
```

Then, unplug and reinsert your Notebook Adapter to clear Windows of any lingering semaphore issues from rubyserial, and give it another shot!

I'll leave this issue open for a few days just to make sure it works for you :+1:

**Comment by MuddledBox** [comment]
@synthead My "notebook adapter" is known working in emulated systems like Windows 98 SE, so I can confirm with the fix you implemented works for me in Windows 11. No updates besides updating to the newest version! Syncs with watch and everything.

**Comment by synthead** [comment]
Upgraded timex_datalink_client in timex_datalink_crt, too:

- https://github.com/synthead/timex_datalink_crt/pull/12
